name: Release tagged commit.

on: [push]

jobs:
  getTag:
    runs-on: windows-latest
    steps:
      - name: GET TAG NAME
        run: echo $GITHUB_REF_NAME
  doRelease:
    runs-on: windows-latest
    steps:
      - name: CREATE RELEASE
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: versions/$GITHUB_REF_NAME.md
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
